### ISSUE TITLE
Directory chooser dialog does not show anything meaningful on Linux

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle-client#10]
After clicking on "Add build" I get this:

![image](https://github.com/gradle/gradle-client/assets/349154/4ad86880-e14d-4c0e-9222-ad47adbae3af)

So that's not really meaningful 😉 

Running on Fedora Linux 40, KDE spin, with Wayland.

**Comment by eskatos** [comment]
Arg, not useful at all indeed.
We simply use `JFileChooser` and don't have any Swing customisation in the code so I wonder what is causing this.
Could you try changing your KDE/GTK theme to see if it does change something?

**Comment by sschuberth** [comment]
Alternatively, as I was looking into a solution for https://github.com/oss-review-toolkit/ort-workbench which has similar problems, consider checking any of these:

- https://github.com/vinceglb/FileKit
- https://github.com/Wavesonics/compose-multiplatform-file-picker
- https://github.com/jakobkmar/pacmc/blob/main/pacmc-gui/src/jvmMain/kotlin/net/axay/pacmc/gui/util/FileChooser.kt

**Comment by eskatos** [comment]
Thanks!
FileKit uses the AWT file dialog on Linux and it is quite awful. The other two require `lwjgl` which is a huge library for that purpose. It feels wrong that this is that complicated to show a file dialog.
I'll give these a try and see

**Comment by sschuberth** [comment]
> FileKit uses the AWT file dialog on Linux and it is quite awful.

And using [FileKit also does not solve the problem](https://github.com/oss-review-toolkit/ort-workbench/issues/276#issuecomment-2182472948), as I've just verified.

For the record, [this](https://github.com/JetBrains/compose-multiplatform/issues/1279) seems to be the upstream issue.

**Comment by eskatos** [comment]
[compose-multiplatform-file-picker](https://github.com/Wavesonics/compose-multiplatform-file-picker) repository has been archived yesterday.

> Currently this project is unmaintained. If you want an alternative I will recommend [FileKit](https://github.com/vinceglb/FileKit)

🤷

**Comment by eskatos** [comment]
This looked like the right solution to this problem but it looks abandoned.

* https://github.com/Wavesonics/compose-multiplatform-file-picker/pull/123

**Comment by sschuberth** [comment]
Another option could be https://github.com/WonderzGmbH/nativefiledialog-java

**Comment by eskatos** [comment]
I gave it a try today but it fails on silicon macs
* https://github.com/WonderzGmbH/nativefiledialog-java/issues/20

**Comment by sschuberth** [comment]
Thanks for reporting those issues upstream, though!

**Comment by vinceglb** [comment]
Hi! I'm a contributor of FileKit. 

We have just released [a new version](https://github.com/vinceglb/FileKit/releases/tag/0.7.0) improving support for Linux on JVM target. Now FileKit uses:
- [XDG Desktop Portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html) on Linux to select files and folders and save files. You can see the implementation [here](https://github.com/vinceglb/FileKit/blob/f79231af0444edeabe06ca1e33f885aca66068aa/filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/xdg/XdgFilePickerPortal.kt). AWT File Dialog is used as a fallback if XdgFilePickerPortal is not available.
- On Windows, FileKit uses JNA to access the native file dialog. [Here](https://github.com/vinceglb/FileKit/blob/main/filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/windows/api/JnaFileChooser.kt) is the implementation.
- Same on macOS, we use JNA for accessing the native file dialog. The implementation [here](https://github.com/vinceglb/FileKit/blob/main/filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/mac/MacOSFilePicker.kt).

FileKit contains all the modifications proposed in this PR https://github.com/Wavesonics/compose-multiplatform-file-picker/pull/123 

We're still working on improving support on all the platforms. JVM one is probably the most complex to implement 😅

If you decide to give FileKit a try and encounter any issues, don't hesitate to create an issue 👌 

I hope it helps!

**Comment by sschuberth** [comment]
Great stuff @vinceglb, that new *FileKit* version actually [works for me](https://github.com/oss-review-toolkit/ort-workbench/pull/286)!

**Comment by eskatos** [comment]
Great stuff indeed @vinceglb!
I was able to make use of FileKit in #26

**Comment by eskatos** [comment]
Actually, I get `Directory picker is not supported on Linux yet` and picking directories is the only thing we're interested in for this project 😿 

I guess we would need at least https://github.com/vinceglb/FileKit/pull/70 before we can adopt this, or do the fallback ourselves which I'm not ready for Today :)

**Comment by eskatos** [comment]
I ended up changing https://github.com/gradle/gradle-client/pull/26 to only use FileKit on Mac and Windows. It's already nicer on these systems.

This doesn't fix this issue though.

A workaround for now is to type or paste a path directly in the field of the file picker if shows up as in the OP screenshot or in the Gradle Client UI fields of the next screen.

**Comment by vinceglb** [comment]
I published a [new version 0.8.0](https://github.com/vinceglb/FileKit/releases) of FileKit:
- This PR is merged https://github.com/vinceglb/FileKit/pull/81: now on Linux we try to use XDG Portal, then awt.FileDialog. JFileChooser is used as fallback
- There are also big improvements on Windows for dialogs UI consistencies (including folder picker dialog)

**Comment by eskatos** [comment]
Thank you @vinceglb !

This is working nicely according to my tests on Linux
* https://github.com/gradle/gradle-client/pull/27
