### ISSUE TITLE
Crashing with "Unknown error" when opening a project

### ISSUE THREAD

**Issue by zsmb13** [gradle/gradle-client#20]
Version 1.0.1 (1.0.1) according to the app, downloaded from the [1.1.0 GitHub release](https://github.com/gradle/gradle-client/releases/tag/1.1.0), running on macOS.

Tried opening these projects, both fail the same way:
* https://github.com/gradle/declarative-samples-kotlin-app
* https://github.com/gradle/declarative-samples-java-app

![image](https://github.com/user-attachments/assets/c5432939-e8f6-4c25-843d-243864c8ea0d)

**Comment by eskatos** [comment]
Thank you for the report Márton!

**Comment by eskatos** [comment]
1.1.1 is out fixing this
https://github.com/gradle/gradle-client/releases/tag/1.1.1

**Comment by zsmb13** [comment]
The new version is still crashing for me when just starting it from Applications, but now the UI under the crash navigates to a new screen

![image](https://github.com/user-attachments/assets/69f53ed7-670d-42de-8e41-fe00a858d760)

Interestingly, it works if I dig into the contents of the app and run it from terminal (with `/Applications/GradleClient.app/Contents/MacOS/GradleClient`)
